# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#
source= /home/lzka/.cache/wal/colors-hyprland.conf

$font = GoogleSans Bold

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = HDMI-A-1
    path = $wallpaper
    blur_passes = 2
    blur_size = 5
    brightness = 0.6
}

input-field {
    monitor = HDMI-A-1
    size = 10%, 4.5%
    outline_thickness = 0
    inner_color = rgba(109,109,109, 0) # no fill

    check_color = transparent 120deg
    fail_color = rgba(245, 87, 87, 0) 40deg

    font_color = $color6
    fade_on_empty = false
    rounding = 100%

    font_family = $font
    placeholder_text = Enter Password
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.2
    dots_spacing = 0.4

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 50
    halign = center
    valign = bottom
}

label {
	monitor = HDMI-A-1
	text = cmd[update:60000] date +"%A, %B %d"
	font_family = $font
	position = 0, -100
	valign = top
}

# TIME
label {
    monitor = HDMI-A-1
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 80
    color = $color6
    font_family = $font

    position = 0, -120
    halign = center
    valign = top
}

label {
	monitor = HDMI-A-1
	text = $USER

	font_size = 15
	font_family = $font
	position = 0, 95
	valign = bottom
}
