font_size 11.0
font_family JetBrainsMono
font_bold Bold
background_opacity 0.8

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# Include pywal colors
include $HOME/.cache/wal/colors-kitty.conf
# END_KITTY_THEME
